# Generated by Django 4.0.3 on 2022-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.IntegerField(default=175),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='client_secret',
            field=models.IntegerField(default=176),
            preserve_default=False,
        ),
    ]
