# Generated by Django 4.0.3 on 2022-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_client_id_alter_user_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='farzana hadifa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='npm',
            field=models.CharField(default=1906398534, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.IntegerField(default=908),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_secret',
            field=models.IntegerField(default=381),
        ),
    ]
